###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class CustomerAnalysis(BaseModel):
    core_problem: Optional[str] = None
    business_consequences: Optional[str] = None
    ideal_customer_profile: Optional[str] = None
    key_stakeholders: List[str]
    anticipated_objections: List[str]

class DynamicInputContext(BaseModel):
    content: Optional[str] = None
    audience_type: Optional[str] = None
    scenario: Optional[str] = None
    tone: Optional[str] = None
    pages: Optional[str] = None
    meeting_deal_summary: Optional[str] = None
    file_context: Optional[str] = None

class ImageElement(BaseModel):
    id: Optional[str] = None
    type: Optional[str] = None
    x: Optional[int] = None
    y: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    src: Optional[str] = None
    alt: Optional[str] = None
    caption: Optional[str] = None
    prompt: Optional[str] = None
    style: Optional["ImageStyle"] = None

class ImageElementEdit(BaseModel):
    id: Optional[str] = None
    type: Optional[str] = None
    x: Optional[int] = None
    y: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    src: Optional[str] = None
    alt: Optional[str] = None
    caption: Optional[str] = None
    prompt: Optional[str] = None
    style: Optional["ImageStyleEdit"] = None

class ImageStyle(BaseModel):
    borderRadius: Optional[str] = None
    objectFit: Optional[str] = None
    marginBottom: Optional[str] = None

class ImageStyleEdit(BaseModel):
    borderRadius: Optional[str] = None
    objectFit: Optional[str] = None
    marginBottom: Optional[str] = None

class MarketPosition(BaseModel):
    market_context: Optional[str] = None
    unique_value_proposition: Optional[str] = None
    data_proof: List[str]
    social_proof: List[str]
    technical_proof: List[str]

class OutlinePoint(BaseModel):
    text: Optional[str] = None

class OutlineSection(BaseModel):
    id: Optional[int] = None
    title: Optional[str] = None
    points: List[str]

class PresentationInput(BaseModel):
    id: Optional[int] = None
    title: Optional[str] = None
    outline: List["OutlineSection"]

class SlideContent(BaseModel):
    slide_id: Optional[str] = None
    background: Optional[str] = None
    content: List[Union["SlideElement", "ImageElement"]]

class SlideContentWithType(BaseModel):
    slide_id: Optional[str] = None
    background: Optional[str] = None
    content: List[Union["SlideElementEdit", "ImageElementEdit"]]

class SlideDetail(BaseModel):
    id: Optional[int] = None
    title: Optional[str] = None
    objective: Optional[str] = None
    key_content_elements: List[str]
    visual_concept: Optional[str] = None
    sales_narrative: Optional[str] = None
    strategic_justification: Optional[str] = None

class SlideEditRequest(BaseModel):
    slide: Optional["SlideContentWithType"] = None
    editPrompt: Optional[str] = None
    theme: Optional[str] = None

class SlideElement(BaseModel):
    id: Optional[str] = None
    x: Optional[int] = None
    y: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    html: Optional[str] = None

class SlideElementEdit(BaseModel):
    id: Optional[str] = None
    type: Optional[str] = None
    x: Optional[int] = None
    y: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    html: Optional[str] = None

class StrategicPresentationOutline(BaseModel):
    title: Optional[str] = None
    id: Optional[int] = None
    strategic_plan: Optional["StrategicSalesPlan"] = None
    slides: List["SlideDetail"]

class StrategicSalesPlan(BaseModel):
    presenter_role: Optional[str] = None
    presentation_task: Optional[str] = None
    primary_cta: Optional[str] = None
    customer_analysis: Optional["CustomerAnalysis"] = None
    market_position: Optional["MarketPosition"] = None
