###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class ExtractedInfo(BaseModel):
    fullName: Optional[str] = None
    emailAddress: Optional[str] = None
    requestDetails: Optional[str] = None
    urgencyLevel: Optional[types.Urgency] = None

class Parameter(BaseModel):
    name: Optional[str] = None
    type: Optional[str] = None
    description: Optional[str] = None
    required: Optional[bool] = None

class Plan(BaseModel):
    steps: List["ToolCall"]

class Resume(BaseModel):
    name: Optional[str] = None
    email: Optional[str] = None
    experience: List[str]
    skills: List[str]

class Tool(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    parameters: List["Parameter"]
    returnType: Optional[str] = None

class ToolCall(BaseModel):
    toolName: Optional[str] = None
    arguments: Dict[str, Optional[str]]
    resultName: Optional[str] = None
    description: Optional[str] = None
    dependsOn: List[str]

class Tools(BaseModel):
    name: Optional[str] = None
    args: Dict[str, Optional[str]]
